In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sklearn import set_config; set_config(display='diagram')
from package.train_baseline import TrainBaseline
from package.train_city import TrainCity
from package.train_store import TrainStore
from package.train_family import TrainFamily
import pandas as pd
import numpy as np
import requests
import joblib
import json

# Train Baseline (Original)

In [3]:
X_train, y_train, X_predict, pipe, preprocessor = TrainBaseline()

In [4]:
X_train

year  month      family  store_nbr  onpromotion
0      2013      1  AUTOMOTIVE          1            0
1      2013      1  AUTOMOTIVE          2            0
2      2013      1  AUTOMOTIVE          3            0
3      2013      1  AUTOMOTIVE          4            0
4      2013      1  AUTOMOTIVE          5            0
...     ...    ...         ...        ...          ...
99787  2017      8     SEAFOOD         50           11
99788  2017      8     SEAFOOD         51           11
99789  2017      8     SEAFOOD         52            7
99790  2017      8     SEAFOOD         53            7
99791  2017      8     SEAFOOD         54            2

[99792 rows x 5 columns]

In [5]:
y_train

0        4.219508
1        4.672829
2        5.225747
3        4.787492
4        4.897840
           ...   
99787    5.685680
99788    6.642873
99789    4.921636
99790    4.219508
99791    3.637586
Name: sales, Length: 99792, dtype: float64

In [6]:
X_predict

year  month      family  store_nbr  onpromotion
0     2017      8  AUTOMOTIVE          1            0
1     2017      8  AUTOMOTIVE          2            0
2     2017      8  AUTOMOTIVE          3            0
3     2017      8  AUTOMOTIVE          4            0
4     2017      8  AUTOMOTIVE          5            0
...    ...    ...         ...        ...          ...
1777  2017      8     SEAFOOD         50           13
1778  2017      8     SEAFOOD         51           18
1779  2017      8     SEAFOOD         52           13
1780  2017      8     SEAFOOD         53            5
1781  2017      8     SEAFOOD         54            2

[1782 rows x 5 columns]

In [7]:
job = joblib.load('model_baseline.joblib')
job

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat_tr',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  ['store_nbr', 'family',
                                                   'year', 'month'])])),
                ('linearregression', LinearRegression())])

In [8]:
job.score(X_train,y_train)

0.6927092576680287

In [9]:
p = job.predict(X_predict).tolist()
p = [np.exp(i) for i in p]
p = np.array(p) 
p

array([8.17647817e+02, 1.11142698e+03, 2.39981958e+03, ...,
       1.11420285e+00, 1.60796468e+02, 4.09705694e+02])

# Train Model (City L1)

In [10]:
X_train, y_train, X_predict, pipe, preprocessor = TrainCity()

In [11]:
X_train

year  month           city
0     2013      1         Ambato
1     2013      1       Babahoyo
2     2013      1        Cayambe
3     2013      1         Cuenca
4     2013      1          Daule
...    ...    ...            ...
1227  2017      8        Quevedo
1228  2017      8          Quito
1229  2017      8       Riobamba
1230  2017      8        Salinas
1231  2017      8  Santo Domingo

[1232 rows x 3 columns]

In [12]:
y_train

0       4.950948e+05
1       1.622901e+05
2       3.144708e+05
3       4.158465e+05
4       1.615544e+05
            ...     
1227    1.546352e+05
1228    5.882149e+06
1229    1.262265e+05
1230    1.474699e+05
1231    4.628482e+05
Name: sales, Length: 1232, dtype: float64

In [13]:
X_predict

year  month           city
0   2017      8         Ambato
1   2017      8       Babahoyo
2   2017      8        Cayambe
3   2017      8         Cuenca
4   2017      8          Daule
5   2017      8      El Carmen
6   2017      8     Esmeraldas
7   2017      8       Guaranda
8   2017      8      Guayaquil
9   2017      8         Ibarra
10  2017      8      Latacunga
11  2017      8       Libertad
12  2017      8           Loja
13  2017      8        Machala
14  2017      8          Manta
15  2017      8         Playas
16  2017      8           Puyo
17  2017      8        Quevedo
18  2017      8          Quito
19  2017      8       Riobamba
20  2017      8        Salinas
21  2017      8  Santo Domingo

In [14]:
job = joblib.load('model_city.joblib')
job

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat_tr',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  ['year', 'month', 'city'])])),
                ('linearregression', LinearRegression())])

In [15]:
job.score(X_train,y_train)

0.9156995981156713

In [16]:
p = job.predict(X_predict).tolist()
p = [np.exp(i) for i in p]
p = np.array(p) 
p

/tmp/ipykernel_11557/250019157.py:2: RuntimeWarning: overflow encountered in exp
  p = [np.exp(i) for i in p]


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf])

# Train Model (Store L2)

In [17]:
X_train, y_train, X_predict, pipe, preprocessor = TrainStore()

In [18]:
X_train

year  month           city  store_nbr
0     2013      1         Ambato         23
1     2013      1         Ambato         50
2     2013      1       Babahoyo         31
3     2013      1        Cayambe         11
4     2013      1         Cuenca         37
...    ...    ...            ...        ...
3019  2017      8       Riobamba         14
3020  2017      8        Salinas         25
3021  2017      8  Santo Domingo          5
3022  2017      8  Santo Domingo         16
3023  2017      8  Santo Domingo         21

[3024 rows x 4 columns]

In [19]:
y_train

0       11.943701
1       12.740370
2       11.997141
3       12.658647
4       12.329930
          ...    
3019    11.745833
3020    11.901379
3021    11.888922
3022    11.492147
3023    12.298015
Name: sales, Length: 3024, dtype: float64

In [20]:
X_predict

year  month           city  store_nbr
0   2017      8         Ambato         23
1   2017      8         Ambato         50
2   2017      8       Babahoyo         31
3   2017      8        Cayambe         11
4   2017      8         Cuenca         37
5   2017      8         Cuenca         39
6   2017      8         Cuenca         42
7   2017      8          Daule         27
8   2017      8      El Carmen         54
9   2017      8     Esmeraldas         43
10  2017      8       Guaranda         19
11  2017      8      Guayaquil         24
12  2017      8      Guayaquil         26
13  2017      8      Guayaquil         28
14  2017      8      Guayaquil         29
15  2017      8      Guayaquil         30
16  2017      8      Guayaquil         32
17  2017      8      Guayaquil         34
18  2017      8      Guayaquil         51
19  2017      8         Ibarra         15
20  2017      8      Latacunga         12
21  2017      8      Latacunga         13
22  2017      8       Libertad         36
23  2017      8           Loja         38
24  2017      8        Machala         40
25  2017      8        Machala         41
26  2017      8          Manta         52
27  2017      8          Manta         53
28  2017      8         Playas         35
29  2017      8           Puyo         22
30  2017      8        Quevedo         33
31  2017      8          Quito          1
32  2017      8          Quito          2
33  2017      8          Quito          3
34  2017      8          Quito          4
35  2017      8          Quito          6
36  2017      8          Quito          7
37  2017      8          Quito          8
38  2017      8          Quito          9
39  2017      8          Quito         10
40  2017      8          Quito         17
41  2017      8          Quito         18
42  2017      8          Quito         20
43  2017      8          Quito         44
44  2017      8          Quito         45
45  2017      8          Quito         46
46  2017      8          Quito         47
47  2017      8          Quito         48
48  2017      8          Quito         49
49  2017      8       Riobamba         14
50  2017      8        Salinas         25
51  2017      8  Santo Domingo          5
52  2017      8  Santo Domingo         16
53  2017      8  Santo Domingo         21

In [21]:
job = joblib.load('model_store.joblib')
job

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat_tr',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  ['year', 'month', 'city',
                                                   'store_nbr'])])),
                ('linearregression', LinearRegression())])

In [22]:
job.score(X_train,y_train)

0.5993945822656733

In [23]:
p = job.predict(X_predict).tolist()
p = [np.exp(i) for i in p]
p = np.array(p) 
p

array([8.97197459e+05, 2.01398318e+06, 1.77040475e+06, 2.16068855e+06,
       1.52618429e+06, 1.57463058e+06, 3.54636652e+02, 1.63735673e+06,
       5.39942942e+05, 1.45061767e+06, 1.61197187e+06, 1.25540495e+06,
       6.21470517e+05, 1.42256018e+06, 1.40810485e+03, 6.31257253e+05,
       4.61837672e+05, 1.44496224e+06, 2.58600559e+06, 9.43934918e+05,
       7.26572645e+05, 9.29300564e+05, 4.54677543e+05, 1.63097328e+06,
       1.35212434e+06, 1.11658028e+06, 2.35247685e+00, 1.91369251e+04,
       5.05251953e+05, 1.84703161e+02, 1.32080241e+06, 9.96993969e+05,
       1.60568738e+06, 4.19750139e+06, 1.30032527e+06, 2.21192780e+06,
       1.83375255e+06, 1.86262995e+06, 2.40102491e+06, 7.79498661e+05,
       1.39504538e+06, 4.22153808e+05, 1.76615916e+03, 5.10286396e+06,
       4.29704227e+06, 3.24357768e+06, 4.86918680e+06, 2.68902034e+06,
       3.64685241e+06, 1.07380476e+06, 7.35137253e+05, 1.28016560e+06,
       9.36589158e+05, 6.54829568e+02])

# Train Model (Family L3)

In [24]:
X_train, y_train, X_predict, pipe, preprocessor = TrainFamily()

In [25]:
X_train

year  month           city  store_nbr                      family
0      2013      1         Ambato         23                  AUTOMOTIVE
1      2013      1         Ambato         23                   BABY CARE
2      2013      1         Ambato         23                      BEAUTY
3      2013      1         Ambato         23                   BEVERAGES
4      2013      1         Ambato         23                       BOOKS
...     ...    ...            ...        ...                         ...
99787  2017      8  Santo Domingo         21                     POULTRY
99788  2017      8  Santo Domingo         21              PREPARED FOODS
99789  2017      8  Santo Domingo         21                     PRODUCE
99790  2017      8  Santo Domingo         21  SCHOOL AND OFFICE SUPPLIES
99791  2017      8  Santo Domingo         21                     SEAFOOD

[99792 rows x 5 columns]

In [26]:
y_train

0         4.248495
1        -2.302585
2         2.890372
3         9.796014
4        -2.302585
           ...    
99787     7.940331
99788     7.834199
99789    10.019346
99790     0.693147
99791     4.521789
Name: sales, Length: 99792, dtype: float64

In [27]:
X_predict

year  month           city  store_nbr                      family
0     2017      8         Ambato         23                  AUTOMOTIVE
1     2017      8         Ambato         23                   BABY CARE
2     2017      8         Ambato         23                      BEAUTY
3     2017      8         Ambato         23                   BEVERAGES
4     2017      8         Ambato         23                       BOOKS
...    ...    ...            ...        ...                         ...
1777  2017      8  Santo Domingo         21                     POULTRY
1778  2017      8  Santo Domingo         21              PREPARED FOODS
1779  2017      8  Santo Domingo         21                     PRODUCE
1780  2017      8  Santo Domingo         21  SCHOOL AND OFFICE SUPPLIES
1781  2017      8  Santo Domingo         21                     SEAFOOD

[1782 rows x 5 columns]

In [28]:
job = joblib.load('model_family.joblib')
job

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat_tr',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  ['year', 'month', 'city',
                                                   'store_nbr', 'family'])])),
                ('linearregression', LinearRegression())])

In [29]:
job.score(X_train,y_train)

0.6916893767585824

In [30]:
p = job.predict(X_predict).tolist()
p = [np.exp(i) for i in p]
p = np.array(p) 
p

array([5.60105411e+02, 1.59176546e+00, 2.73507249e+02, ...,
       1.40789466e+02, 3.16513107e-01, 3.00050946e+01])

# API Single Prediction

In [31]:
### API tests

year=['2017','2017','2017']
month=['8','8','8']
family=['AUTOMOTIVE','AUTOMOTIVE','AUTOMOTIVE']
store_nbr=['1','2','3']
onpromotion=['0','0','0']

d = dict(
        year=[int(i) for i in year],
        month=[int(i) for i in month],
        family=[str(i) for i in family],
        store_nbr=[int(i) for i in store_nbr],
        onpromotion=[int(i) for i in onpromotion]
    )
print(d)
X = pd.DataFrame(d)
X

{'year': [2017, 2017, 2017], 'month': [8, 8, 8], 'family': ['AUTOMOTIVE', 'AUTOMOTIVE', 'AUTOMOTIVE'], 'store_nbr': [1, 2, 3], 'onpromotion': [0, 0, 0]}


year  month      family  store_nbr  onpromotion
0  2017      8  AUTOMOTIVE          1            0
1  2017      8  AUTOMOTIVE          2            0
2  2017      8  AUTOMOTIVE          3            0

In [32]:
job = joblib.load('model_baseline.joblib')
dict(enumerate(job.predict(X).flatten(),1))

{1: 6.7064317017793655, 2: 7.013400036841631, 3: 7.783148840069771}

In [35]:
url = 'http://127.0.0.1:8000/predict-year'
params = {
    'year': year,
    'month': month,
    'family': family,
    'store_nbr': store_nbr,
    'onpromotion': onpromotion
}

response = requests.get(url, params=params)
response.json() 

JSONDecodeError: [Errno Expecting value] Internal Server Error: 0

In [34]:
url = 'http://127.0.0.1:8000/predict-single?'
params = {
    'year': year[0],
    'month': month[0],
    'family': family[0],
    'store_nbr': store_nbr[0],
    'onpromotion': onpromotion[0]
}

response = requests.get(url, params=params)
response.json()

{'sales': 0.0}